name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build -r --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        path: target/debug/neo-meting
